### PR TITLE
GCC & Clang Latest, Versioning Fixes

### LINKED ISSUE #128: Add GCC 12-14 as well as Clang 16-18 to CI/CD and fix warnings
Currently, the CI/CD workflows test GCC versions 5-11. The latest version however is GCC 14. To ensure support for these new compiler releases, we should add them to the CI/CD pipeline. The same goes for the newer versions of Clang mentioned in the title.

Further, from local compilations, it looks like GCC 12 onwards triggers a few warnings with the XAD code. These warnings should be carefully assessed and fixed (not suppressed). 

We could use a container [like this one](https://github.com/foonathan/docker/pkgs/container/gcc) to build for GCC version 7 to 14 onwards and [this one](https://github.com/foonathan/docker/pkgs/container/clang) for Clang 11-18. 

We can probably drop support for GCC 5 and 6 at that point, as they are very old. This would allow us to remove the older containers that are used for builds at the moment, which have issues supporting newer versions of the GitHub actions.

### PR DESCRIPTION
**Pull request by raneamri**
# Description

- Added GCC 12-14 to CI
- Added Clang 16-18 to CI
- Added `AlignedAllocator` and `NullAlignedAllocator` to simulate allocation failure
- Merged `AlignedDeleter` into the above, along with `detail::aligned_free` and `detail::aligned_alloc`
- Edited `StdCompatibility.hpp` description to reflect some design choices
- `StdCompatibilityTempl.Traits` test blocked on MSVC 14.4

Fixes #128 & #160.

## Type of change

-   Bug fix (non-breaking change which fixes an issue)

### CODE REVIEW

File: src/XAD/OperationsContainer.hpp [hunk 1]
```diff
@@ -41,6 +41,19 @@ struct AlignedDeleter
...
+    static void* aligned_alloc(std::size_t alignment, std::size_t size) {
+        return detail::aligned_alloc(alignment, size);
+    }
+};
+
+struct NullAlignedAllocHelper {
+    static void* aligned_alloc(std::size_t, std::size_t) {
+        return nullptr; // simulate failure
+    }
+};
```
Comment (xcelerit-team) [inline src/XAD/OperationsContainer.hpp:54]: As this is for testing only, it should be moved to the test folder. End users should not have access to it.

And how about moving the `AlignedAllocHelper` out of this file into a file of its own, and include the body of the `detail::aligned_alloc` function with all the ifdef etc into it. So that we have a separate header with the memory allocations that we include in the 3 containers that use it?

**Comment by xcelerit-team** [comment]
It looks like the `is_arithmetic` and related type traits issues are not really solvable with the latest MSVC 14.4. It is likely a compiler built-in in recent versions, as it was working just a few month back with a slightly older release. Now, even when using a full template specialisation as `template <> struct is_arithmetic<xad::AD> : true_type {}; ` it still doesn't resolve to `true` in MSVC. 

I suggest to use `ifdef` to disable that test if MSVC with toolset 14.4 or newer is used, using preprocessor variables. 

Also note that with C++17 and beyond, the `std::is_arithmetic_v` template variables work just fine (the next test).

File: src/XAD/AlignedAllocator.hpp [hunk 2]
```diff
@@ -0,0 +1,99 @@
+/*******************************************************************************
+
+   TODO
```
Comment (xcelerit-team) [inline src/XAD/AlignedAllocator.hpp:3]:
```suggestion
   Cross platform helpers for aligned memory allocations.
```

File: src/XAD/AlignedAllocator.hpp [hunk 3]
```diff
@@ -0,0 +1,99 @@
...
+#include <memory>
+#include <type_traits>
+#include <vector>
+
+namespace xad {
+namespace detail {
+
+
+}  // namespace detail
+}  // namespace xad
```
Comment (xcelerit-team) [inline src/XAD/AlignedAllocator.hpp:38]: Please remove

File: src/XAD/ChunkContainer.hpp [hunk 4]
```diff
@@ -34,85 +35,10 @@
...
 
-// cross-platform aligned (de-)allocation
-
-#if defined(__APPLE__) || defined(__ANDROID__) ||                                                  \
-    (defined(__linux__) && defined(__GLIBCXX__) && !defined(_GLIBCXX_HAVE_ALIGNED_ALLOC))
-#include <cstdlib>
-
-#if defined(__APPLE__)
-#include <AvailabilityMacros.h>
-#endif
```
Comment (xcelerit-team) [inline src/XAD/ChunkContainer.hpp:45]: I think this include is missing in the AlignedAllocator header - it allows us to check the versions, etc. Otherwise it'll just use the fallback version of the allocator.

File: src/XAD/AlignedAllocator.hpp [hunk 5]
```diff
@@ -0,0 +1,99 @@
...
+    
+    static inline void aligned_free(void* ptr) {
+    #if defined(_WIN32)
+        ::_aligned_free(ptr);
+    #else
+        free(ptr);
+    #endif
+    }
+
+    void operator()(void* ptr) const { this->aligned_free(ptr); }
```
Comment (xcelerit-team) [inline src/XAD/AlignedAllocator.hpp:94]: maybe add a comment here that you added this operator so that the struct can be used as a deleter for std smart pointers.

File: src/XAD/StdCompatibility.hpp [hunk 6]
```diff
@@ -1,7 +1,10 @@
 /*******************************************************************************
 
    Placing XAD math functions into the std namespace for std::log type
-expressions to work, as well as specialising numeric_limits.
+   expressions to work, as well as specialising numeric_limits.
+
+   This paritally violates the C++ standard's "don't specialize std templates"
+   rule but is necessary for integration with other libraries.
```
Comment (xcelerit-team) [inline src/XAD/StdCompatibility.hpp:7]: Can you add a similar note to the `doc/refs/headers.md` file for this header? Just a short note.

**Review by xcelerit-team — CHANGES_REQUESTED** [review]
Nearly there - just a few cosmetics.

**Review by auto-differentiation-dev — APPROVED** [review]

**Review by xcelerit-team — APPROVED** [review]
